### ISSUE TITLE
Can't initialize lecdown

### ISSUE THREAD

**Issue by Toofarto** [jasonchoimtt/lecdown#1]
**Error Message**
```
Traceback (most recent call last):
  File "/usr/local/bin/lecdown", line 4, in <module>
    import lecdown.main
ImportError: No module named lecdown.main
```

**Comment**
/usr/local/bin/lecdown:

```python
#!/usr/local/opt/python/bin/python2.7


import lecdown.main

lecdown.main.main()
````

Maybe the first line should indicate to run this script by python3 instead of python2? 

**Related information**
default python version: Python 2.7.11

**Comment by jasonchoimtt** [comment]
Seems like the installation instruction was incorrect; you have to use `pip3` to install it. In fact, the first line is auto-generated by pip.

I will update the readme.
